Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-06, with the labels that each got.

#284 Pr cxod8 to dockerhub
  .circleci/config.yml
Labels: size/XS

#287 remove java8 from jar name
  .circleci/config.yml
Labels: size/XS

#289 update cxflow version to 1.6.1
  build-11.gradle
  build-cxod.gradle
  build.gradle
Labels: size/XS

#296 pr-nightly-clean-eks
  .circleci/config.yml
Labels: size/S

#308 Temporarily exclude publishprocess tests
  build.gradle
Labels: size/XS

#310 split automation tests to run in parallel in separated packages
  .circleci/config.yml
  build.gradle
Labels: size/L

#317 update version to 1.6.2
  build-11.gradle
  build-cxgo.gradle
  build.gradle
Labels: size/XS
