Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-11, with the labels that each got.

#494 "fix wrong hints in log message when team creation fail
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Labels: bug

#500 Fixed - Add 'Training' ticket markdown link
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: bug

#516 fix null pointer exception when SCA version is null
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: bug

#518 fix null pointer exception when SCA version is null (#516)
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: skip-release-notes

#512 Create wiki-publisher.yml
  .github/workflows/wiki-publisher.yml
  docs/Config-As-Code.md
  docs/CxGO--(below-version-1.6.12).md
  docs/CxGO--(from-1.6.12).md
  docs/Integration-with-CxSCA.md
Labels: size/L

#521 Update wiki-publisher.yml
  .github/workflows/wiki-publisher.yml
Labels: size/XS, skip-release-notes

#528 Support SCA Results in GitLab Security Dashboard
  src/main/java/com/checkmarx/flow/config/GitLabProperties.java
  src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
Labels: enhancement

#522 Pr add cxgo integration tests
  .circleci/config.yml
  build.gradle
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/RepoService.java
  src/test/java/com/checkmarx/flow/cucumber/common/repoServiceMockers/GithubServiceMocker.java
  src/test/java/com/checkmarx/flow/cucumber/common/repoServiceMockers/GitlabServiceMocker.java
  src/test/java/com/checkmarx/flow/cucumber/common/repoServiceMockers/RepoServiceMocker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/RunCxGoScanRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
  src/test/java/com/checkmarx/jira/JiraTestUtils.java
  src/test/resources/application.yml
  src/test/resources/cucumber/features/integrationTests/cxgo/cxgoScanProcessing.feature
Labels: skip-release-notes

#529 update sdk version and update wiki page
  build-11.gradle
  build.gradle
  docs/Configuration.md
Labels: size/S

#530 Updated & Streamlined Labs
  docs/Execution.md
  docs/Labs.md
Labels: size/XS

#533 Pr remove internal secrets
  .circleci/config.yml
Labels: size/S, skip-release-notes

#535 Fix Cx-Flow SCA vulnerabilities
  build-11.gradle
  build-cxgo.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, size/S

#540 fix ast integration tests
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
Labels: skip-release-notes

#548 fix comments-script config example
  docs/Work-with-external-scripts.md
Labels: documentation, size/XS, skip-release-notes

#545 Cx-Flow gets Cx-GO configuration from Cx-Integrations [328]
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/config/CxIntegrationsProperties.java
  src/main/java/com/checkmarx/flow/config/external/CxGoConfigFromWebService.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/exception/ReposManagerException.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/GitAuthUrlGenerator.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/ReposManagerService.java
  src/main/resources/application.yml
  src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
  src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationsRunner.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/PublishingSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sast/config/OverwritingProjectConfigSteps.java
  src/test/java/com/checkmarx/flow/utils/ScanUtilsTest.java
  src/test/resources/cucumber/features/componentTests/cxIntegrations.feature
Labels: enhancement
