Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-10, with the labels that each got.

#433 Update CxGo SDK to version 0.1.38
  build-cxgo.gradle
Labels: size/XS

#434 Added badges and link to wiki
  README.md
Labels: size/XS

#437 Fixed Bug-286: Issue on merge requests with info severity results
  src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
Labels: bug

#438 Support reading bean configuration from remote repo via Config-Provider component
  build-11.gradle
  build-cxgo.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/aop/LoggingAop.java
  src/main/java/com/checkmarx/flow/config/external/ASTConfig.java
  src/main/java/com/checkmarx/flow/constants/FlowConstants.java
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
  src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
  src/main/java/com/checkmarx/flow/controller/FlowController.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/controller/TfsController.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoTestRunner.java
  src/test/resources/cucumber/features/integrationTests/configProvider/remoteRepo/configProviderRemoteRepo.feature
Labels: enhancement

#442 Switch cx-spring-boot-sdk ts dependency to ltd
  build-11.gradle
  build.gradle
Labels: size/XS, skip-release-notes

#443 orb circleci/aws-eks had upgraded
  .circleci/config.yml
Labels: size/S, skip-release-notes

#451 Pr natalie prerelease
  .circleci/config.yml
  .github/release-drafter.yml
  build-11.gradle
  build-cxgo.gradle
  build.gradle
Labels: enhancement, size/M

#452 Update config-provider with new version: 1.0.9
  build-11.gradle
  build-cxgo.gradle
  build.gradle
Labels: size/XS, skip-release-notes

#453 Added publishing artifacts to github pre-release on each successful pipeline on Develop branch
  .circleci/config.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: size/XS

#449 fix repo project ID set for scan request
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
Labels: bug

#454 Enable AST CLI & Remote Env tests
  build.gradle
  helm/cxflow/templates/external-secret.yaml
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
  src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
Labels: size/XS, skip-release-notes

#457 fix bug tracker None not functioning as expected
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
Labels: bug

#460 Change pre-release artifacts generation options
  .circleci/config.yml
Labels: size/XS, skip-release-notes

#472 use latest authenticator-release
  .circleci/config.yml
Labels: size/XS, skip-release-notes

#473 Create directory path if not exist + Fix SCA cli scan test
  src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: size/S

#470 Pr add gitlab e2e tests
  .circleci/config.yml
  helm/cxflow/templates/deployment.yaml
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
  src/test/resources/cucumber/data/input-files-toscan/cx.gitlab.configuration
  src/test/resources/cucumber/features/e2eTests/HookProperties_GITLAB.properties
  src/test/resources/cucumber/features/e2eTests/genericEndToEnd.feature
Labels: skip-release-notes

#482 Fix for config-as-code broken for BB server push events (#481)
  src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
Labels: bug

#487 update cx-sdk version to fix SCA issues logic
  build.gradle
Labels: bug, size/XS

#489 Fix release drafter to ignore prereleases
  .github/workflows/release-drafter.yml
Labels: size/XS, skip-release-notes
