Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-09, with the labels that each got.

#408 Update CxGo SDK to 0.1.34
  build-cxgo.gradle
Labels: size/XS

#406 add sca latestProjectResults filters tests
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: skip-release-notes

#409 Added support for multiple optional SCM's instances for GitLab & ADO
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/config/ScmConfigOverrider.java
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/controller/WebhookController.java
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/PublishingSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sast/config/OverwritingProjectConfigSteps.java
Labels: enhancement

#410 Fixed - Sonar potential NPE on ServiceNowTracker
  src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
Labels: skip-release-notes

#412 delete Cx-project on ado delete branch event
  src/main/java/com/checkmarx/flow/config/ADOProperties.java
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/resources/cucumber/features/componentTests/delete-branch.feature
Labels: enhancement

#413 fix parse component tests
  src/test/java/com/checkmarx/flow/cucumber/component/parse/RunningCxFlowSteps.java
Labels: skip-release-notes

#415 Added new PR comments summary design
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
Labels: enhancement

#414 Pr ts feature/shard manager
  .DS_Store
  build-11.gradle
  build-cxgo.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/aop/LoggingAop.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
Labels: enhancement

#418 fix exception log in jira service
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: bug

#417 support configurable sast comment
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/service/ExternalScriptService.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
  src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
  src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptRunner.java
  src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/resources/cucumber/data/input-scripts-sample/invalid-return-type-comment-script.groovy
  src/test/resources/cucumber/data/input-scripts-sample/invalid-syntax-script-comment.groovy.invalid
  src/test/resources/cucumber/data/input-scripts-sample/parse-branch-name-comment.groovy
  src/test/resources/cucumber/data/input-scripts-sample/sast-standard-comment.groovy
  src/test/resources/cucumber/data/input-scripts-sample/special-characters-comment-script.groovy
  src/test/resources/cucumber/features/componentTests/configure-sast-comment-script.feature
Labels: enhancement

#420 Pr nimrod remove redundant GitHub comments
  src/main/java/com/checkmarx/flow/custom/GitHubIssueCommentFormatter.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: skip-release-notes

#425 BBCloud : Fix for broken source link due to forward slash(/) present in branch name.
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: priority:high

#424 Publish SCA results into local files
  build.gradle
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/ImmutableIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/ScaCsvParameters.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/JAXBHelper.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: enhancement

#427 Pr orly fix jira test project
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
Labels: skip-release-notes

#428 Fixed Markdown of PR summary in BitBucket
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
Labels: bug

#431 Update SCA tests with new expected results
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/S, skip-release-notes
