Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-07, with the labels that each got.

#332 Update config.yml
  .circleci/config.yml
Labels: size/XS

#340 Added releaseDrafter github action to automatically generate release
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: size/M

#344 Credentials validation removed from SCA cx-config test
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
  src/test/resources/cucumber/features/integrationTests/cxconfig.feature
Labels: skip-release-notes

#346 Fixed: Normalize project name in CLI mode to prevent bad characters on project name
  src/main/java/com/checkmarx/flow/service/SastScanner.java
Labels: bug

#347 Fix for component tests to avoid NPE in sastPR/ThresholdSteps
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
Labels: skip-release-notes

#348 update cxflow version 1.6.3
  build-11.gradle
  build-cxgo.gradle
  build.gradle
Labels: size/M, skip-release-notes

#351 Added new recommended fix link to Bug tracker's issues
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/publishprocess/RunPublishProcessSteps.java
  src/test/java/com/checkmarx/jira/IJiraTestUtils.java
  src/test/java/com/checkmarx/jira/JiraTestUtils.java
  src/test/resources/cucumber/features/integrationTests/jira/publish-processing.feature
Labels: enhancement

#352 Fix CLI Execution from processing results twice
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
Labels: bug

#354 Added Partial Fix for bug-201: vulnerability scanners are part of scanRequest
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
  src/test/java/com/checkmarx/flow/utils/ScanUtilsTest.java
  src/test/resources/cucumber/features/e2eTests/genericEndToEnd.feature
Labels: bug

#355 Pr nimrod sca filters tests new repo
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: skip-release-notes

#361 Pr us 192 cli tests
  .circleci/config.yml
  build.gradle
  src/main/java/com/checkmarx/flow/constants/SCATicketingConstants.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/IntegrationTestContext.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliStepsRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliStepsRunner.java
  src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: enhancement

#362 Fixed: NPE fix for potential DDos attack
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
Labels: bug

#366 remove test namespace from clean-eks job
  .circleci/config.yml
Labels: size/XS, skip-release-notes
