Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-08, with the labels that each got.

#370 get cxflow logs to end to end tests
  .circleci/config.yml
Labels: size/L, skip-release-notes

#372 Fixed: config as code parameters overrides scan-request object instead of properties files
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigTestRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
  src/test/resources/cucumber/data/input-files-toscan/cx.config.src
Labels: bug

#373 add k8s external secret per deployment
  .circleci/config.yml
Labels: size/S, skip-release-notes

#379 Added new AST Jira Integration test
  .circleci/config.yml
  build.gradle
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/bugtrackers/jira/AstTicketsCreationViaJiraSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/bugtrackers/jira/RunAstTicketsCreationViaJiraSteps.java
  src/test/resources/cucumber/data/sample-ast-results/5-findings-2-high-3-medium.json
  src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
Labels: skip-release-notes

#375 Fix for Issue #360 : Added PR feedback in case of existing active scan.
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
Labels: bug

#380 Bitbucket (Cloud & Server) Support for Config-as-Code and Auto Profiling.
  src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
  src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/Content.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/History.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/Links.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/Meta.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/Value.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Children.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Content.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Path.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Value.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
Labels: enhancement

#391 Added support for multiple optional SCM's instances
  build.gradle
  src/main/java/com/checkmarx/flow/config/OptionalScmInstanceProperties.java
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/config/ScmConfigOverrider.java
  src/main/java/com/checkmarx/flow/config/ScmConfigParams.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
  src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/PublishingSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/PublishTicketsWithOptionalScmConfSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/RunPublishTicketsWithOptionalScmConfSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sast/config/OverwritingProjectConfigSteps.java
  src/test/resources/cucumber/features/integrationTests/jira/publish-processing.feature
Labels: enhancement

#392 In case optional instance value are not defined - throw an exception
  src/main/java/com/checkmarx/flow/config/ScmConfigOverrider.java
Labels: skip-release-notes

#393 Pr nimrod fix unstable GitHub tests
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/PublishTicketsWithOptionalScmConfSteps.java
Labels: skip-release-notes

#397 Fixed: Remove hard coded auto profile setting to TRUE on GitHubController flow
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
Labels: bug

#394 Azure DevOps : Support for Config-as-code and Auto Profiling.
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/dto/azure/Content.java
  src/main/java/com/checkmarx/flow/dto/azure/Value.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/utils/ADOUtils.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Labels: enhancement

#402 Code changes to avoid duplicate code warning in Sonar
  src/main/java/com/checkmarx/flow/service/ADOService.java
Labels: skip-release-notes

#400 improve pr-comment tests
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/AstCommonSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerConfiguration.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestConfiguration.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/scans/SCARemoteRepoScanSteps.java
  src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature
Labels: skip-release-notes

#407 Fixes Issue #405 : Exception thrown in case of blank email template name.
  src/main/java/com/checkmarx/flow/config/FlowConfig.java
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/EmailService.java
Labels: bug
