Repository checkmarx-ltd/cx-flow, pull requests merged in 2020-12, with the labels that each got.

#551 fix engine configuration override
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: bug

#552 Fix SAST vulnerabilities
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/GitAuthUrlGenerator.java
  src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: skip-release-notes

#559 Scanner specific propoerty (.yml) files for Docker, GH Actions, CircleCI orb etc.
  src/main/resources/application-ast.yml
  src/main/resources/application-cxgo.yml
  src/main/resources/application-sast.yml
  src/main/resources/application-sca.yml
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: size/L

#564 Support Cx-Go scans with over GitLab with Cx-Integrations
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
Labels: enhancement

#562 fix merge block for ast
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
  src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature
Labels: bug

#578 Fix for #566: Log initialization error during CxFlow startup
  build.gradle
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Labels: size/XS

#579 Fixed bug #574: SCA do not follow-up when creating an issue
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
Labels: bug

#576 Fix vulnerability line links in merge/pull request
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: bug

#581 Fixed bug 335: Cx-Go SCM tickets are always opened with 'new' status
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: bug

#585 Support Cx-Flow : Cx-Integrations E2E flow
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: enhancement

#584 Add new SCA issues resolving test
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/github/ScaResolveIssueRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/github/ScaResolveIssueSteps.java
  src/test/resources/cucumber/data/sample-sca-results/16-findings-6-high-10-medium-resolver.json
  src/test/resources/cucumber/data/sample-sca-results/16-findings-6-high-10-medium.json
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: skip-release-notes

#588 Update WIKI description for SAST filter-state
  docs/Configuration.md
  docs/Home.md
Labels: documentation, size/XS
