Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-03, with the labels that each got.

#664 support delete temporary folders for linux
  build-11.gradle
  build.gradle
Labels: size/XS

#672 Fixed misplaced single quotation
  templates/gitlab/v2/Checkmarx.gitlab-ci.yml
Labels: size/XS

#670 Support SCA async scan in with 'None' bug-tracker type
  build-11.gradle
  build.gradle
  docs/Images/SCA2.png
  docs/Integration-with-CxSCA.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
Labels: bug

#681 - Updated docker name
  templates/gitlab/v2/Checkmarx.gitlab-ci.yml
Labels: size/XS

#682 Grammar fixes in the 'Thresholds' wiki page
  docs/Thresholds-and-policies.md
Labels: size/M

#684 Updated the SDK version to 0.4.94
  build-11.gradle
  build.gradle
Labels: size/XS

#686 Added documentation for Proxy Configuration with cxflow.
  docs/Proxy-Configuration.md
  docs/Proxy-and-HTTPS-Configuration.md
Labels: size/M

#690 Remove SCA negative test & fix SCA wiki
  docs/Images/SCA2.png
  docs/Images/SCA2A.png
  docs/Integration-with-CxSCA.md
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/teams.feature
Labels: skip-release-notes

#689 Fix merge comment - CLI mode
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/constants/FlowConstants.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Labels: bug

#698 Feature/license
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  LICENSE.TXT
Labels: size/L
