Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-12, with the labels that each got.

#871 Added warning log for jira-field-name when set to Labels
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  docs/YML-Example-Files.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S

#872 Enable project-level custom fields
  build-11.gradle
  build.gradle
  docs/Config-As-Code.md
  docs/Configuration.md
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/M

#867 small changes in Cx-flow iast integration.
  src/main/java/com/checkmarx/flow/service/IastService.java
Labels: size/S

#877 added feature to support branched project from base project
  build-11.gradle
  build.gradle
  docs/Configuration.md
  docs/CxSAST-Version-9.0.md
  docs/YML-Example-Files.md
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Labels: size/S

#876 Pr enable scan level custom fields
  build-11.gradle
  build.gradle
  docs/Config-As-Code.md
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/S

#879 fix slash not present in repoUrl and issues with branched project
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/S

#854 Update Checkmarx.gitlab-ci.yml
  templates/gitlab/v3/Checkmarx.gitlab-ci.yml
Labels: size/XS

#855 add more automatically statuses for jira
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
Labels: size/XS

#834 Add scan comment sample script
  docs/External-Scripts.md
  src/main/resources/samples/ScanComment.groovy
Labels: size/M

#885 ADO CRLF update
  Dockerfile
  src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
Labels: size/XS

#887 fixed branched project regression
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Labels: size/XS

#888 Log4j 2.16.0 uptake in java8 and java11 build gradle
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/S

#889 Support for providing Min-Max Heap size for docker
  Dockerfile
  docs/Execution.md
Labels: size/S

#892 documentation update along with comments
  README.md
  src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
Labels: size/M
