Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-01, with the labels that each got.

#589 Align cx-go integrations DTO with new name
  src/main/java/com/checkmarx/flow/config/external/CxGoConfigFromWebService.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
Labels: skip-release-notes

#590 Fix bug #560 - Branch name extraction
  src/main/java/com/checkmarx/flow/service/GitHubService.java
Labels: bug

#594 Support BitBucket E2E flow with Cx-Integrations
  build-11.gradle
  build-cxgo.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
  src/main/java/com/checkmarx/flow/controller/FlowController.java
  src/main/java/com/checkmarx/flow/controller/TfsController.java
  src/main/java/com/checkmarx/flow/controller/WebhookController.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/EmailService.java
  src/main/java/com/checkmarx/flow/service/FilterFactory.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: enhancement

#596 Added documentation for the cx-flow.zip-exclude option
  docs/Configuration.md
  docs/Excluding-Files-from-Zip-Archive.md
Labels: size/M

#597 Support SCA zip scan
  build-11.gradle
  build.gradle
  docs/Integration-with-CxSCA.md
  src/main/java/com/checkmarx/flow/service/ASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/zip_scan/ScaZipScanRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/zip_scan/ScaZipScanSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: enhancement

#600 fix git lab merge git url scan
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: bug

#602 Fix SCA direct libraries vulnerabilities
  build-11.gradle
  build-cxgo.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: skip-release-notes

#604 Avoid race condition - add wait for pull request status not pending
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Labels: bug

#599 change sdk version to 68 - support AST authorization for local sources scan
  build-11.gradle
  build.gradle
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
Labels: size/M

#607 Pr asaf jira script new
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptRunner.java
  src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptSteps.java
  src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/invalid-return-type-project-key-script.groovy
  src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/invalid-syntax-project-key-script.groovy
  src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/jira-standard-project-key.groovy
  src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/parse-jira-project-key.groovy
  src/test/resources/cucumber/features/componentTests/configure-jira-project-key-script.feature
Labels: enhancement

#608 Duplicate the apk upgrade command
  Dockerfile
Labels: size/XS

#614 Fix SCA open, update & close tickets mechanism
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/CodeBashingService.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
  src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/ado/ScaIssuesCreationSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: bug

#615 Remove SCA severity & score detail from ticket key & title
  src/main/java/com/checkmarx/flow/constants/SCATicketingConstants.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/ado/ScaIssuesCreationSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: enhancement

#616 Pr orly common incorporation
  build-11.gradle
  build.gradle
Labels: size/XS

#605 Update exclude documentation
  docs/Configuration.md
Labels: size/S

#617 Upgrade SDK version to 0.4.73: support Cx-GO not exploitable results
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/IssueService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Labels: enhancement

#619 Update SCA apiUrl domain
  src/main/resources/application-sca.yml
  src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
  src/test/resources/application-sca.yml
  src/test/resources/cucumber/data/input-files-toscan/cx.config.src
Labels: skip-release-notes

#618 Corrected the broken file links for Wiki.
  docs/Labs.md
Labels: documentation, size/XS

#621 fix cxgo tests
  src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Labels: skip-release-notes

#622 Upgrade SDK version to 0.4.75: Fix NPE in filterValidator
  build-11.gradle
  build.gradle
Labels: bug, size/XS

#625 Upgrade SDK version to 0.4.77: Support SCA scan with cx-origin header
  build-11.gradle
  build.gradle
Labels: enhancement, size/XS

#626 Gitlab - Reduced comments notifications on pull requests + Tests
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/dto/RepoComment.java
  src/main/java/com/checkmarx/flow/dto/gitlab/Comment.java
  src/main/java/com/checkmarx/flow/dto/gitlab/ObjectAttributes.java
  src/main/java/com/checkmarx/flow/dto/gitlab/Project.java
  src/main/java/com/checkmarx/flow/dto/gitlab/Repository.java
  src/main/java/com/checkmarx/flow/dto/gitlab/User.java
  src/main/java/com/checkmarx/flow/exception/GitLabClientRuntimeException.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/main/java/com/checkmarx/flow/service/RepoService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature
Labels: enhancement
