Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-09, with the labels that each got.

#782 Pr iast 2646 azure integration
  docs/CxIAST-Integration.md
  docs/Images/IAST4.png
  docs/Images/iast_jira_issue.png
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/controller/IastController.java
  src/main/java/com/checkmarx/flow/dto/iast/CreateIssue.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/IastService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/iast/IastCliSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/iastCli.feature
Labels: size/L

#806 ADO thread status update and PR status update as per scan result
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
Labels: size/M

#818 Fix colon not allowed in JIRA issue label
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XS

#822 updated CxSBSDK version to support scascantimeout
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/resources/application-sca.yml
Labels: size/S

#824 Jira custom issue prefix feature
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/M

#827 Fix for bitbucket PR webhook broken
  src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Author.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/FromRef.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Links.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/ToRef.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerMergeHandler.java
Labels: size/S

#829 exclude-folders works without trailing /. So updated Configuration.md file
  Release.txt
  docs/Configuration.md
  docs/CxSCA-Integration.md
Labels: size/XS

#826 Fix hyphen not allowed in JIRA issue label
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XS
