Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-02, with the labels that each got.

#630 Prevent ConcurrentModificationException error while execute batch mode
  .circleci/config.yml
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: bug

#631 Support SCA project teams assignment
  build-11.gradle
  build.gradle
  docs/Integration-with-CxSCA.md
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/RunSCATeamsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/teams.feature
Labels: enhancement

#632 SCA project team assignment test & WIKI minor amendments
  docs/Integration-with-CxSCA.md
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
Labels: skip-release-notes

#635 Upgrade SDK version - fix SCA vulnerabilities
  build-11.gradle
  build.gradle
Labels: size/XS, skip-release-notes

#636 Fix SCA vulnerabilities
  build-11.gradle
  build-cxgo.gradle
  build.gradle
Labels: size/S, skip-release-notes

#639 Support SCA policy management for pull-request fail/break build process
  build-11.gradle
  build.gradle
  docs/Images/SCA-policy-creation.png
  docs/Integration-with-CxSCA.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementRunner.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: enhancement

#641 Support include source files option for SCA zip scan
  build-11.gradle
  build.gradle
  docs/Integration-with-CxSCA.md
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
Labels: enhancement

#643 fix AST tests after AST version upgrade
  build-11.gradle
  build.gradle
  src/test/resources/cucumber/features/componentTests/astComments.feature
  src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
Labels: size/S

#646 Pr asaf fix cli gitlab notes
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: bug

#649 Fix Gitlab Date parser issue
  src/main/java/com/checkmarx/flow/service/GitLabService.java
Labels: bug

#657 Update WebHook-Registration.md
  docs/WebHook-Registration.md
Labels: documentation, size/XS

#659 Support SCA team assignment within config-as-code
  build-11.gradle
  build.gradle
  docs/Integration-with-CxSCA.md
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
Labels: enhancement

#663 Remove unused product from scan request
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Labels: skip-release-notes
