Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-04, with the labels that each got.

#705 Pr wiki updates
  README.md
  docs/AWS-Fargate-Deployment.md
  docs/Architecture.md
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/CodeBashing.md
  docs/Config-As-Code.md
  docs/Configuration.md
  docs/CxConfigProvider.md
  docs/CxSAST-Version-9.0.md
  docs/CxSCA-Integration.md
  docs/Development.md
  docs/External-Scritps.md
  docs/Proxy-and-HTTPS-Configuration.md
  docs/Thresholds-and-policies.md
  docs/Tutorials.md
  docs/WebHook-Registration.md
  docs/Workflows.md
  src/main/resources/samples/CxConfig.json
  src/main/resources/samples/cx-flow-full.json
  src/main/resources/samples/cx-flow.json
Labels: size/XL

#706 fix gitlab comments integration tests
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Labels: size/XS, skip-release-notes

#707 Removed Jira as the default bug tracker
  src/main/resources/application.yml
Labels: size/XS

#708 Upgrade SDK version to 0.4.95
  build-11.gradle
  build.gradle
Labels: skip-release-notes

#709 SCA config as code required all fields to be define
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/cxgo/cxgoScanProcessing.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: enhancement

#715 Upgrade SDK version to 0.4.97
  build-11.gradle
  build.gradle
Labels: enhancement, size/XS

#717 remove AST integrarion tests
  .circleci/config.yml
Labels: size/S
