Repository checkmarx-ltd/cx-flow, pull requests merged in 2021-11, with the labels that each got.

#863 False positive handling for SCA
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/S

#864 sdk update to support sca branch scanning
  build-11.gradle
  build.gradle
Labels: size/XS

#868 Feature for ssh support per project
  build-11.gradle
  build.gradle
  docs/Config-As-Code.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/dto/FlowOverride.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/M

#866 PR Documentation Fixes
  README.md
  docs/Configuration.md
  docs/CxSAST-Version-9.0.md
  docs/Tutorials.md
  docs/YML-Example-Files.md
  src/main/resources/application-9.0.yml
  src/main/resources/application-full.yml
Labels: size/M

#869 fix for all branches being scanned when no protected branches are defined
  docs/Configuration.md
  docs/YML-Example-Files.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
Labels: size/S

#870 Base alpine used instead of one from openjdk
  Dockerfile
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GitHubApiHandler.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
Labels: size/M
