Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-11, with the labels that each got.

#1123 Added scan id CLI parameter for project mode
  Dockerfile
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/M

#1118 Vulnerability fix
  build-11.gradle
  build.gradle
Labels: size/S

#1137 jira 9 fix
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/negative_tests/JiraUnreachableSteps.java
Labels: size/M

#1136 vulnerabilities-fix
  build-11.gradle
  build.gradle
Labels: size/S

#1127 Clarify documentation of regular expressions and protected branches
  docs/Configuration.md
Labels: size/XS

#1126 Fixed GitLab CI/CD repoUrl Creation
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/XS

#1139 CXFLW-586 Pr groovyscript
  Dockerfile
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/HelperService.java
Labels: size/S

#1140 CXFLW-583 Pr breakthebuild cxflw 583
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/test/resources/cucumber/features/componentTests/sca-thresholds.feature
Labels: size/M

#1141 Pr breakthebuild cxflw 583 Removing
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S
