Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-08, with the labels that each got.

#1071 Fixed GitHub Summary length issue
  .circleci/config.yml
  build-11.gradle
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
Labels: size/L

#1075 CXFLW-539 refactored code and updated docs
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/M

#1076 CXFLW-540 Fixed Jira team issue for sca
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XS

#1078 Pr cxflw 175 secondary rate limit
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
Labels: size/M

#1080 PR CLI branch filtering fix
  docs/Configuration.md
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S

#1090 CXFLW-551 CxFlow adds the GitLab CI token to the repository URL in Jira issues created
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XS

#1089 CXFLW-525 Fixed inconsistent project name for sca
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
Labels: size/S

#1093 SAST Migration from 8.9 to 9.4
  .circleci/config.yml
  Dockerfile
  README.md
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/zip_scan/ScaZipScanSteps.java
  src/test/resources/application.yml
  src/test/resources/cucumber/features/integrationTests/codebashing/codebashingLessons.feature
Labels: size/M
