Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-10, with the labels that each got.

#1113 CXFLW-573 GitLab merge requests create an endless loop of scans #1079
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
Labels: size/S

#1117 Jira 9 support added
  docs/Prerequisites-and-Requirements.md
  src/main/java/com/checkmarx/flow/config/FlowConfig.java
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/jira9X/FieldSchema.java
  src/main/java/com/checkmarx/flow/jira9X/IssueFields.java
  src/main/java/com/checkmarx/flow/jira9X/IssueType.java
  src/main/java/com/checkmarx/flow/jira9X/Project.java
  src/main/java/com/checkmarx/flow/jira9X/StandardOperation.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XL

#1119 CXFLW-572 Fixed of Bitbucket default Branch name issue
  src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Avatar.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Avatar__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Avatar__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Avatar__3.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/BranchName.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Branches.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Clone.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Commits.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Downloads.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Forks.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Hooks.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Html.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Html__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Html__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Html__3.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Links.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Links__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Links__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Links__3.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Mainbranch.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/OverrideSettings.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Owner.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Project.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Pullrequests.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Self.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Self__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Self__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Self__3.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Source.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Tags.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Watchers.java
  src/main/java/com/checkmarx/flow/dto/bitbucket/mainBranch/Workspace.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerDeleteHandler.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerMergeHandler.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerPushHandler.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
Labels: size/XXL
