Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-07, with the labels that each got.

#1045 Fixed closing and reopening of issues for all bug trackers
  src/main/java/com/checkmarx/flow/service/IssueService.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/M

#1047 Merging Development changes in my branch
  build-11.gradle
  build.gradle
  docs/Config-As-Code.md
  src/main/java/com/checkmarx/flow/dto/FlowOverride.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/IssueService.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/M

#1040 CXFLW-378: SCA zip scan fails when run in pipeline
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S

#1050 CXFLW-378: SCA zip scan fails when run in pipeline
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S

#1053 Fixed Summary Issue with multiple vulnerabilities of the same type in…
  .circleci/config.yml
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
Labels: size/S

#1056 Sendgrid 2 (new PR)
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/EmailService.java
  src/main/resources/templates/generic-event-message.html
  src/main/resources/templates/scan-completed-successfully.html
Labels: size/M

#1058 Taking all code from dev to my branch Including test case results
  .circleci/config.yml
  Dockerfile
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Config-As-Code.md
  docs/CxSAST-Version-9.0.md
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/dto/FlowOverride.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/main/java/com/checkmarx/flow/service/EmailService.java
  src/main/java/com/checkmarx/flow/service/IssueService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidator.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/resources/templates/generic-event-message.html
  src/main/resources/templates/scan-completed-successfully.html
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/L

#1060 Pr gh780 gitlab pagination
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/test/java/com/checkmarx/flow/cucumber/component/parse/RunningCxFlowSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/parse/VerifyingCxFlowReportSteps.java
  src/test/resources/application.yml
  src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
  src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
Labels: size/L

#1064 Pagintion code change along with tst case file change
  .circleci/config.yml
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
  src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
Labels: size/L

#1067 Adding null check
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S
