Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-02, with the labels that each got.

#921 Fixed fasterxml related vulnerabilities
  build-11.gradle
  build.gradle
Labels: size/XS

#911 Scan Queuing Change from PR #857 (added scanQueuing and scanQueuingTimeout size/M)
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/M

#922 Upgrade spring boot version to 2.6.1
  build-11.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: size/M

#918 Wiki config as code fixes
  docs/Config-As-Code.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/dto/FlowOverride.java
Labels: size/L

#923 When cx-flow.mail.cc is not set, NullPointerException
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/service/EmailService.java
Labels: size/M

#926 fixed null pointer exception in ConfigurationOverrider
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/S

#927 [JIRA CXFLW-100] Update CodeBashing API and documentation in Wiki
  docs/CodeBashing.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S

#929 Feature to support bitbucket PR update event
  src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
Labels: size/S

#932 Pr bitbucket delete event support
  docs/Delete-Branch.md
  src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
Labels: size/M

#940 Pr provide custom fields in jira for sca
  build-11.gradle
  build.gradle
  docs/AWS-Fargate-Deployment.md
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/CxSCA-Integration.md
  docs/YML-Example-Files.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/L

#942 [SAST Scan] Provide support for Generic Issue Format of Sonar
  src/main/java/com/checkmarx/flow/config/SonarQubeProperties.java
  src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
Labels: size/L

#943 [SCA Scan] Provide support for Generic Issue Format of Sonar
  docs/Tutorials.md
  src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
Labels: size/M
