Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-09, with the labels that each got.

#1098 Code change for test case fix
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/XS

#1097 SCA Resolver Integration with Cx-Flow
  Dockerfile
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
Labels: size/M

#1104 CXFLW-577 Fix for Git dashboard.
  src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
Labels: size/M

#1094 CXFLW-379 (GH 950): Map latest scan custom fields to JIRA fields
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#1084 Set the teamName obtained by the groovy script
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Labels: size/XS

#1069 Disregarding Lows and Infos for the e-mail summary.
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/service/EmailService.java
Labels: size/S

#1095 CXFLW-569 (GH 1018) ignoring filter-severity in postback mode
  src/main/java/com/checkmarx/flow/controller/FlowController.java
Labels: size/S

#1105 Vulnerability fix
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
Labels: size/XS

#1103 CXFLW-516 Details about the reason of a scan failure & CXFLW-570 Gitlab Integration Documentation
  build-11.gradle
  build.gradle
  docs/Tutorials.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/controller/FlowController.java
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/XL

#1106 Pr verchange
  build-11.gradle
  build.gradle
Labels: size/XS

#1107 Snake-yaml vulnerability fix
  build-11.gradle
  build.gradle
Labels: size/XS

#1108 Updated SDK version
  build-11.gradle
  build.gradle
Labels: size/XS

#1111 Added Config as code for SCA Resolver
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/S
