Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-04, with the labels that each got.

#987 Fixed issues related to cx-branch not working correctly
  build-11.gradle
  build.gradle
  docs/Execution.md
  docs/Images/branchedProjectOnPull.png
  docs/Images/branchedProjectScan.png
  docs/Images/fbranch.png
  docs/Images/no_project_present.PNG
  docs/Tutorials.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
Labels: size/M

#990 [JIRA:CXFLW-233] CxFlow (GH 904): Add SCA filter for vulnerabilities that break Policy Violations
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/ScaFilterFactory.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
Labels: size/M

#989 Upgraded Spring boot,Spring Core and Tomcat version
  build-11.gradle
  build.gradle
Labels: size/S

#991 [JIRA:CXFLW-119] Gitlab command line should support merge title parameter
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/XS

#994 [JIRA:CXFLW-234] Documentation - Update README and Wiki to move Post Back Action and Development Section
  README.md
  docs/Architecture.md
  docs/CxSAST-Version-9.0.md
  docs/Development.md
  docs/Prerequisites-and-Requirements.md
  docs/Workflows.md
Labels: size/L

#1000 fixed documentation for Scan Comment groovy script
  docs/External-Scripts.md
Labels: size/XS

#995 Fixed recommended version in sca result summary
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/XS

#1002 Added documentation for cx-sast roles required by a user of cxflow
  docs/CxSAST-Version-9.0.md
Labels: size/S

#1005 [JIRA:CXFLW-47] CxFlow: Don't group findings for Sarif - GH Action Security Updates
  build-11.gradle
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
  src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
Labels: size/XXL

#997 [JIRA:CXFLW-119] Documentation for merge title and merge id in Wiki
  Dockerfile
  docs/Configuration.md
Labels: size/XS

#998 Handled ProjectName with embedded#
  src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
Labels: size/XS

#999 added JAVA_HOME env variable in dockerfile
  Dockerfile
Labels: size/XS

#996 corrected typo error from pen-to open
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
Labels: size/XS

#1007 Documentation update and addition of new sample yml files
  README.md
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  docs/Delete-Branch.md
  docs/Execution.md
  docs/Images/sarif-report-1.png
  docs/Images/sarif-report-2.png
  docs/Images/sarif-report-3.png
  src/main/resources/application-azure.yml
  src/main/resources/application-csv.yml
  src/main/resources/application-github.yml
  src/main/resources/application-jira.yml
Labels: size/L

#1001 Remove the references of codebashing from Wiki
  docs/AWS-Fargate-Deployment.md
  docs/CodeBashing.md
  docs/Configuration.md
  docs/CxSAST-Version-9.0.md
  docs/Tutorials.md
  docs/YML-Example-Files.md
Labels: size/M

#1004 Pr case insensitive jira statuses
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S
