Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-05, with the labels that each got.

#1010 [JIRA:CXFLW-47] CxFlow: Don't group findings for Sarif - GH Action Security Updates
  build-11.gradle
  build.gradle
Labels: size/XS

#1013 fixed pipeline kubernetes issue
  .circleci/config.yml
Labels: size/M

#1012 [JIRA:CXFLW-836] added scope documentation.
  build-11.gradle
  build.gradle
  docs/Configuration.md
Labels: size/XS

#1019 JDK8 new version uptake in the docker image and other pipeline fixes.
  .gitignore
  Dockerfile
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/EmailService.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
  src/main/java/com/checkmarx/flow/service/SendGridService.java
  src/main/resources/application.yml
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/L

#1015 Add support for after/before/failed scan email notifications
  build-11.gradle
  docs/Config-As-Code.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/M
