Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-03, with the labels that each got.

#947 Feature for CxXML as bug-tracker for CxSCA
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
Labels: size/M

#945 Issues in Jira should not be closed on re-run of other/alternate scan for same project.
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/CliMode.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#952 Fixed SCA vulnerability in spring-core package
  build.gradle
Labels: size/XS

#951 Pr parse mode implementation for sca
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/ASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
Labels: size/M

#955 Scan failing due to value of size variable of Azure Repository is large
  src/main/java/com/checkmarx/flow/dto/azure/Repository.java
Labels: size/XS

#956 Update BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
Labels: size/M

#957 Fixed tomcat vulnerability
  build-11.gradle
  build.gradle
Labels: size/XS

#960 Added tutorial for Branched project
  docs/Images/CxSAST_Licensed_Projects.png
  docs/Images/CxSAST_branch_project.png
  docs/Images/CxSAST_default_project.png
  docs/Images/CxSAST_project_count.png
  docs/Images/bp_db1.png
  docs/Images/fbranch.png
  docs/Tutorials.md
Labels: size/S

#961 Added documentation For Scan Queuing and Docker
  docs/Configuration.md
  docs/Execution.md
Labels: size/S

#959 update gitlab template
  templates/gitlab/v3/Checkmarx.gitlab-ci.yml
Labels: size/S

#972 Added documentation For CLI params and Issue summary
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Execution.md
Labels: size/M

#966 Update Tutorials.md
  docs/Tutorials.md
Labels: size/M

#973 Update Tutorials.md
  docs/Tutorials.md
Labels: size/S

#965 added scan-resubmit functionality for CLI mode
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/S

#963 Added Correct Quick start tutorial.
  docs/Home.md
Labels: size/XS

#974 added missing parameters of cx-flow section
  docs/Configuration.md
Labels: size/M

#977 added correct xml scheme link
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/XS

#941 Fix postback Scan Reports
  src/main/java/com/checkmarx/flow/controller/FlowController.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/S

#976 Support suppression of code snippets for Jira tickets
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#978 [JIRA:CXFLW-30] CircleCI - Update ORB and CxFlow wiki documentation
  docs/Tutorials.md
Labels: size/M

#980 updated documentation for CxSAST/CxSCA Result Summary
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Images/CxSAST_Result_Summary.PNG
Labels: size/XS

#982 Fix image not showing in wiki for CxSAST summary
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/XS

#981 Gitlab Security Reports is expecting a string instead of a float
  src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
Labels: size/XS

#984 used proper jql word in the code.
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
Labels: size/S
