Repository checkmarx-ltd/cx-flow, pull requests merged in 2022-01, with the labels that each got.

#896 Feature to provide thresholds via Webhook and log4j version uptake to 2.17.1
  build-11.gradle
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/controller/WebhookController.java
  src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
  src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsCommandLineCommonSteps.java
Labels: size/M

#895 [ADO:587] CxFlow: GH Action Updates - links and attack vector
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/M

#893 Add Security Severity Attribute in Report of SARIF File
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/S

#881 Fix Service Now Integration and add Comment
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
Labels: size/M

#898 [ADO 587] Link to SAST Result and Check for Empty Value In Description
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/S

#884 Add scanResubmit property to config-as-code
  docs/Config-As-Code.md
  src/main/java/com/checkmarx/flow/dto/FlowOverride.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/M

#901 Wiki redesign
  docs/Configuration.md
  docs/CxConfigProvider.md
  docs/Home.md
Labels: size/XL

#900 Feature/841 option to disable comment on pr
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/RepoService.java
Labels: size/M

#903 Shard report fix
  src/main/java/com/checkmarx/flow/controller/FlowController.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsCommandLineCommonSteps.java
Labels: size/L

#907 reverted dockerfile changes to original
  Dockerfile
Labels: size/S

#913 uptake alpine version to 3.15 and Java11 version to 11.0.14_p9-r0
  Dockerfile
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/S

#909 Fixed CxFlow Vulnerabilities
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/test/resources/cucumber/features/componentTests/filter-script.feature
Labels: size/L

#915 Documentation update for post-action-postback-id and settings-override
  docs/Configuration.md
Labels: size/S

#916 Branch project documentation update
  docs/Configuration.md
Labels: size/S
