Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-02, with the labels that each got.

#1168 Changes for SCA Resolver files and log deletion
  Dockerfile
  build-11.gradle
  build.gradle
Labels: size/S

#1159 Document restrict-results-to-branch property.
  docs/Configuration.md
Labels: documentation, size/XS

#1170 Fixed SAST and SCA Order issue
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  docs/CxIAST-Integration.md
  docs/CxSAST-Version-9.0.md
  docs/CxSCA-Integration.md
  docs/Delete-Branch.md
  docs/Thresholds-and-policies.md
  docs/Tutorials.md
  src/main/java/com/checkmarx/flow/service/ASTScanner.java
  src/main/java/com/checkmarx/flow/service/CxGoScanner.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
Labels: size/L

#1173 CXFLW-625 SCA scan failures with Threshold and DevDependencies Ticket No | 00144935
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidator.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
Labels: size/M

#1174 CXFLW-582 Fix For Git pull request scan breakbuild fix
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/S

#1178 ScaResolver Origin Change
  build-11.gradle
  build.gradle
Labels: size/XS

#1179 Pr sca not exp issue
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
Labels: size/XS

#1181 Break Build SAST and SCA Threshold issue fix
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
Labels: size/S

#1171 make result overview collapsible
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/XS

#1182 CXFLW-566 Pr release39 documentation
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  docs/Thresholds-and-policies.md
Labels: size/M

#1183 SCA Vulnerability Fix
  build-11.gradle
  build.gradle
Labels: size/XS

#1187 CXFLW-724 Fix for SAST Default value in arraylist
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
Labels: size/XS

#1193 ScanResubmit Config as Code fix
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/XS
