Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-07, with the labels that each got.

#1244 Tutorial docs fix
  docs/Tutorials.md
Labels: size/XS

#1245 Vulnerabilities fix for version 1.6.41
  build-11.gradle
  build.gradle
Labels: size/XS

#1241 Jira closing issue for SCA
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S

#1246 ADO Pull request fix and sdk version update
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
Labels: size/L

#1247 Pr Version Update
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Labels: size/XS

#1196 Tweak the log masking configuration
  src/main/resources/logback-spring.xml
Labels: size/XS

#1249 Update version.txt
  version.txt
Labels: size/XS

#1255 Vulnerability URL fix for SCA
  Dockerfile
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/XS

#1256 Jira transition docs fix
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/XS
