Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-03, with the labels that each got.

#1197 link-to-SCA-fix
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/XS

#1198 Changed Configuration.ini to Configuration.yml
  Dockerfile
Labels: size/XS

#1201 SonarQube Secondary path issue fix
  src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
Labels: size/M

#1192 fix create team for /scan
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Labels: size/M

#1203 escaping spaces in pr decoration
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/S

#1202 CXFLW-725 Updated documentation
  docs/Prerequisites-and-Requirements.md
Labels: size/S

#1206 CXFLW-719 Break build false
  docs/Thresholds-and-policies.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Labels: size/M

#1204 CXFLW-688 Pr sonarqubeissue
  src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
Labels: size/S

#1208 ScaResolver documentation fix
  docs/CxSCA-Integration.md
Labels: size/XS

#1207 Running-CxFlow-as-a-Windows-Service documentation fix
  docs/Running-CxFlow-as-a-Windows-Service.md
Labels: size/XS

#1210 Scan Comment Documentation fix
  Dockerfile
  docs/External-Scripts.md
Labels: size/S
