Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-11, with the labels that each got.

#1286 CXFLW-966 CxFlow: using System.Tags as an --alt-fields option throws an error
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/config/ADOProperties.java
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
Labels: size/M

#1289 CXFLW-970 Gitlab project issue
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/M

#1290 Added SCA include pattern in Config as code
  Dockerfile
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
Labels: size/S

#1291 Fixed cx-summary property
  Dockerfile
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Labels: size/S

#1287 Added Support for Jira On-premise Personal Access Token
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Tutorials.md
  src/main/java/com/atlassian/jira/rest/client/internal/async/CustomAsynchronousJiraRestClientFactory.java
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#1292 Sast private scan changes
  build-11.gradle
  build.gradle
  docs/Config-As-Code.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
  src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptSteps.java
Labels: size/S

#1294 Security vulnerabilities fix
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Labels: size/S

#1295 CXFLW-1003 Gitlab draft issue fix
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
Labels: size/M

#1297 Added details for version parameter
  docs/Configuration.md
Labels: size/M

#1296 Fix for startColumn -1 in sarif format
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/XS

#1298 Code changes for exceptions
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
Labels: size/M
