Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-04, with the labels that each got.

#1213 Documentation fix
  docs/Configuration.md
  docs/CxSCA-Integration.md
  docs/External-Scripts.md
Labels: size/L

#1215 Documentation update for Jira
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Proxy-and-HTTPS-Configuration.md
  docs/Tutorials.md
Labels: size/M

#1214 Pr cxflw 668 folder exclusion
  docs/Configuration.md
  docs/Thresholds-and-policies.md
Labels: size/XS

#1209 CXFLW-681 Fix For vulnerable project name in SAST
  build-11.gradle
  src/main/java/com/checkmarx/flow/service/HelperService.java
Labels: size/S

#1216 WebHook Params thresholds docs fix
  docs/Configuration.md
Labels: size/S

#1217 CXFLW-659 Merge Id recognized.
  docs/Thresholds-and-policies.md
Labels: size/XS

#1220 On prim Assignee fix
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/S

#1222 CXFLW-753 Added Documentaition for scanID as output variable
  docs/Configuration.md
Labels: size/M
