Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-01, with the labels that each got.

#1153 Jira Cloud Fix
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#1147 CXFLW-639 code for comment added
  .circleci/config.yml
  satyam.crt
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/M

#1156 vulnerability fix
  build-11.gradle
  build.gradle
Labels: size/XS

#1148 Document properties for the waiting for branching to complete
  docs/Configuration.md
Labels: size/XS

#1160 Jira closing of issue fix when filter status configured
  Dockerfile
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/test/java/com/checkmarx/flow/cucumber/component/parse/CxFlowReport.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
  src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
  src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
Labels: size/XXL

#1163 ScaResolver addParams Fix
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/M

#1166 Jira default value fix
  src/main/java/com/checkmarx/flow/jira9X/FieldSchema.java
  src/main/java/com/checkmarx/flow/jira9X/IssueFields.java
  src/main/java/com/checkmarx/flow/jira9X/IssueType.java
  src/main/java/com/checkmarx/flow/jira9X/Project.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/L
