Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-06, with the labels that each got.

#1234 Updated jira docs and sdk version
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/S

#1235 Alpine version update
  Dockerfile
Labels: size/XS

#1237 CXFLW-8 add labels in issues
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/config/GitLabProperties.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
Labels: size/L

#1239 Pr alpineandsdkversoionupdate
  Dockerfile
  build-11.gradle
  build.gradle
Labels: size/S

#1236 CXFLW-812 Added code for scan left active state
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
  src/test/resources/cucumber/features/componentTests/sca-thresholds.feature
  src/test/resources/cucumber/features/componentTests/thresholds.feature
  src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Labels: size/L
