Repository checkmarx-ltd/cx-flow, pull requests merged in 2023-09, with the labels that each got.

#1265 Updated Bitbucket Server Schema and docs
  docs/Configuration.md
  docs/Tutorials.md
  docs/WebHook-Registration.md
  src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Author__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Author__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Commit.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Committer.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Committer__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Committer__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Links__4.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Links__5.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Links__6.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Parent.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Parent__1.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Parent__2.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/PushEvent.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Self__4.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Self__5.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/Self__6.java
  src/main/java/com/checkmarx/flow/dto/bitbucketserver/ToCommit.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerPushHandler.java
Labels: size/XXL

#1266 CXFLW-742 Added additional logging.
  src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/CodeBashingService.java
  src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/L

#1267 CXFLW-829 Added Documentation for AWS buildspec
  docs/Thresholds-and-policies.md
Labels: size/XS

#1272 Jira new labels DEV or PROD
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
Labels: size/S

#1271 pr-CXFLW-998 Added code for Custom fields
  docs/Execution.md
Labels: size/M

#1268 CXFLW-833 Added document for generation JSON Logs from cx-flow
  docs/Troubleshooting.md
Labels: size/M

#1275 Fixed NullPointerException for SCA methods
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/S

#1278 GitLab Merge request Recommended version column fix
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/XS

#1276 Vulnerability Fix for ivy and tomcat
  build-11.gradle
  build.gradle
Labels: size/S

#1277 Fixed Bitbucket server token issue
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerScanEventHandler.java
Labels: size/XS

#1279 null Pointer fix
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
Labels: size/XS

#1281 Added Notice for Java Versions
  README.md
  docs/Home.md
  docs/Prerequisites-and-Requirements.md
Labels: size/S
