Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-01, with the labels that each got.

#1306 CXFLW-924 Adding document changes for ODATA API request.
  docs/Configuration.md
Labels: size/XS

#1307 CXFLW-967 Custom State Result Map
  docs/Configuration.md
Labels: size/XS

#1301 Added latest committer email for JSON bug tracker
  build-11.gradle
  build.gradle
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/controller/GitLabController.java
  src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
  src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/JsonProperties.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerPushHandler.java
Labels: size/M

#1302 Added docker badge in README
  README.md
Labels: size/XS

#1305 Vulnerability fix for 1.6.46 release
  Dockerfile
  build-11.gradle
  build.gradle
Labels: size/S

#1304 Added API to get SCA tags
  build-11.gradle
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Labels: size/M

#1308 CXFLW-993 CXFLW-1128 documentation and added zip utils test case
  build.gradle
  docs/Frequently-Asked-Questions.md
  src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
  src/main/java/com/checkmarx/flow/utils/JAXBHelper.java
  src/main/java/com/checkmarx/flow/utils/ZipUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ziputils/RunZipUtilsTest.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ziputils/zipUtilsSteps.java
  src/test/resources/cucumber/features/ziputils/ziputils.feature
Labels: size/L

#1309 Version Update
  build-11.gradle
  build.gradle
  docs/Thresholds-and-policies.md
Labels: size/XS

#1310 Pr cxflow documentation
  build-11.gradle
  build.gradle
Labels: size/XS
