Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-05, with the labels that each got.

#1344 Fixed setting of project level custom fields
  build-11.gradle
  build.gradle
  version.txt
Labels: size/XS

#1349 pr-CXFLW-1177-comment-pr
  .circleci/config.yml
  README.md
  Release.txt
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
Labels: size/M

#1352 New Https Certificate added in cxflow
  src/test/resources/checkmarx.crt
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/L

#1351 Fixed Jira description overflow issue
  docs/Bug-Trackers-and-Feedback-Channels.md
  src/main/java/com/checkmarx/flow/config/JiraProperties.java
  src/main/java/com/checkmarx/flow/constants/JiraConstants.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S

#1347 Mask GitHub personal access tokens in logs
  src/main/resources/logback-spring.xml
Labels: size/XS

#1348 CXFLW-1093 added code for pattern support in branch list
  src/main/java/com/checkmarx/flow/service/HelperService.java
Labels: size/XS

#1346 CXFLW-979 Opting Out of Bitbucket comment notifications during
  build.gradle
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Labels: size/M

#1353 Added FAQ docs for ADO work items
  docs/Frequently-Asked-Questions.md
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/S

#1354 Added code for incremental scan issue
  build.gradle
  docs/Configuration.md
Labels: size/XS

#1355 Vulnerability fix for 1.7.01
  build-11.gradle
  build.gradle
Labels: size/S

#1357 CXFLW-1050 CXFLW-1086 CXFLW-1217 Fix
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/S

#1358 fix for bitbucket commit
  src/main/java/com/checkmarx/flow/service/ResultsService.java
Labels: size/S
