Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-12, with the labels that each got.

#1405 Added validate branch before config as code
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
Labels: size/M

#1407 added project and scan custom field parameters
  docs/Configuration.md
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
Labels: size/L

#1408 CXFLW-857 Added code for gitlab user
  docs/Frequently-Asked-Questions.md
  docs/cxflow_gitlab_scan_issue.md
Labels: size/S

#1409 CXFLW-1070 Added code for module details in SARIF.
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/L

#1410 CXFLW-1335 updated documentation for default branch issue.
  docs/Configuration.md
Labels: size/XS

#1413 CXFLW-1506 Added code for comment off concurrent PR scans
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
Labels: size/S

#1411 CXFLW-1338 Added code for text and markdown.
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/M

#1414 security fix for verison 1.7.06
  build.gradle
Labels: size/S

#1415 Added documentation for ScaResolver
  docs/CxSCA-Integration.md
Labels: size/S

#1412 CXFLW-1490 added code for upload sarif issue.
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/M
