Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-03, with the labels that each got.

#1327 CXFLOW-1328: Set security-severity in the SARIF SCA report to match the markdown and tags fields
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
  src/test/java/com/checkmarx/flow/custom/SarifSCAIssueTrackerTest.java
Labels: size/L

#1311 Add dynamodb backend for sharding
  build.gradle
Labels: size/XS

#1320 Update Checkmarx logo
  docs/Images/cxLogo.PNG
Labels: size/XS

#1332 Updated Notice message
  README.md
Labels: size/XS

#1334 Pr cxflw 1176 groovyscriptissue
  build.gradle
  docs/Configuration.md
  version.txt
Labels: size/M

#1333 Added new parameter commentUpdate
  docs/Configuration.md
  docs/Home.md
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/config/GitLabProperties.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
  src/main/java/com/checkmarx/flow/service/GitLabService.java
  src/main/java/com/checkmarx/flow/service/RepoService.java
  src/test/java/com/checkmarx/flow/cucumber/component/ast/parse/GitHubCommentsASTSteps.java
Labels: size/M

#1335 CXFLW-916 Scan Location overwrite
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Labels: size/XS

#1331 Added new parameter zip-include for cx-flow
  README.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/utils/ZipUtils.java
  src/test/java/com/checkmarx/flow/cucumber/integration/ziputils/zipUtilsSteps.java
Labels: size/M

#1336 Vulnerability fix for version 1.7.0
  Dockerfile
  build-11.gradle
  build.gradle
  src/main/java/com/checkmarx/flow/config/FlowConfig.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
  src/main/java/com/checkmarx/flow/jira9X/FieldSchema.java
  src/main/java/com/checkmarx/flow/jira9X/IssueType.java
  src/main/java/com/checkmarx/flow/jira9X/Project.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/iast/IastCliSteps.java
Labels: size/M

#1324 Changed id datatype from int to long
  README.md
  src/main/java/com/checkmarx/flow/dto/github/Issue.java
Labels: size/S

#1321 Updated documentation for Jira Skip Update
  README.md
  docs/Bug-Trackers-and-Feedback-Channels.md
Labels: size/M

#1337 Updated springboot tomact version
  build-11.gradle
  build.gradle
Labels: size/S
