Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-10, with the labels that each got.

#1382 Reduce PR decoration changes with configuration
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/L

#1383 Pull decoration refresh and updated
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/config/RepoProperties.java
  src/main/java/com/checkmarx/flow/service/RepoService.java
Labels: size/S

#1386 Added Symbolic link zip feature
  build.gradle
  src/main/java/com/checkmarx/flow/utils/ZipUtils.java
Labels: size/M

#1394 Changed StackTrace logs from error to debug
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/BitBucketService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
Labels: size/M

#1385 Added mapping labels capability like Jira
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/GitHubProperties.java
  src/main/java/com/checkmarx/flow/config/GitLabProperties.java
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/java/com/checkmarx/flow/dto/LabelField.java
Labels: size/XL

#1395 Added exclude parameters for vulnerability
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
  src/main/java/com/checkmarx/flow/service/FilterFactory.java
Labels: size/M

#1388 pr-CXFLW-1296 Improved documentation for GitLab dashboard.
  docs/Tutorials.md
Labels: size/L

#1389 CXFLW-1336 Added code to add snippet in cxflow SARIF report its configurable.
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/M

#1391 CXFLW-1295 Updated documentation regarding branched project
  docs/Configuration.md
Labels: size/S

#1390 CXFLW-1294 Updated documentation for disable clubbing of issues in SARIF.
  docs/Bug-Trackers-and-Feedback-Channels.md
  docs/Images/1.PNG
  docs/Images/2.PNG
Labels: size/S

#1393 CXFLW-1479 Added code for scan cancel on timeout
  docs/Configuration.md
Labels: size/XS

#1396 Added CLI bitbucket pull feature
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/BitBucketProperties.java
Labels: size/M

#1397 CXFLW-1337 sarif-artifact-issueAdded code for artifact issue
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/M

#1398 Fixed Vulnerability for 1.7.04
  build.gradle
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
Labels: size/XS
