Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-04, with the labels that each got.

#1338 Added documentation and circle cir configuration changes
  .circleci/config.yml
  build.gradle
  docs/Configuration.md
  docs/Thresholds-and-policies.md
Labels: size/L

#1339 Fixed vulnerability for logback
  build-11.gradle
  build.gradle
Labels: size/XS

#1345 added scan and project tags for SCA
  Dockerfile
  build-11.gradle
  build.gradle
  docs/CxSCA-Integration.md
  src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
Labels: size/S
