Repository checkmarx-ltd/cx-flow, pull requests merged in 2024-07, with the labels that each got.

#1369 CXFLW-1345 pipeline integration task
  .circleci/config.yml
  Dockerfile
  src/main/java/com/checkmarx/flow/CxFlowApplication.java
  src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsOpenIssueViaCommandLineSteps.java
Labels: size/M

#1360 filter dev, test & indirect dependencies not working
  build.gradle
Labels: size/XS

#1362 Removed codeBashing Training Links
  src/main/java/com/checkmarx/flow/service/IssueService.java
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Labels: size/M

#1363 Fixed Label issue for Info
  src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
Labels: size/XS

#1364 Fixed token leaks
  src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
  src/main/resources/logback-spring.xml
Labels: size/S

#1367 Added ADO git clone feature
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/ADOProperties.java
Labels: size/S

#1372 CXFLW-1223 Added code for prscans-not-triggered
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
  src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/GitHubService.java
Labels: size/S

#1374 CXFLW-1233 Added code for project deletion on PR close event.
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/controller/GitHubController.java
  src/main/java/com/checkmarx/flow/dto/ScanRequest.java
  src/main/java/com/checkmarx/flow/dto/github/PullRequest.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
Labels: size/M

#1376 CXFLW-1236 added code for custom keystore feature
  build.gradle
  docs/Configuration.md
  docs/Proxy-and-HTTPS-Configuration.md
Labels: size/S

#1370 Added bitbucket cloud and server git clone
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/config/BitBucketProperties.java
  src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/cli/iast/IastCliSteps.java
Labels: size/M

#1375 Added support for branches in GitLab CI template
  templates/gitlab/v4/Checkmarx.gitlab-ci.yml
Labels: size/L

#1377 Fixed Jira not closing issues marked Not Exploitable in SAST
  src/main/java/com/checkmarx/flow/service/JiraService.java
Labels: size/S
