Repository checkmarx-ltd/cx-flow, pull requests merged in 2025-04, with the labels that each got.

#1439 PR decoration comments for ADO
  src/main/java/com/checkmarx/flow/controller/ADOController.java
  src/main/java/com/checkmarx/flow/controller/TfsController.java
  src/main/java/com/checkmarx/flow/dto/azure/Comment.java
  src/main/java/com/checkmarx/flow/dto/azure/CommentAuthor.java
  src/main/java/com/checkmarx/flow/dto/azure/CommentLinks.java
  src/main/java/com/checkmarx/flow/dto/azure/CommentSelf.java
  src/main/java/com/checkmarx/flow/dto/azure/Commit.java
  src/main/java/com/checkmarx/flow/dto/azure/CreatedBy.java
  src/main/java/com/checkmarx/flow/dto/azure/PRCommentEvent.java
  src/main/java/com/checkmarx/flow/dto/azure/PRCreatedEvent.java
  src/main/java/com/checkmarx/flow/dto/azure/PullEvent.java
  src/main/java/com/checkmarx/flow/dto/azure/PullRequest.java
  src/main/java/com/checkmarx/flow/dto/azure/Repository.java
  src/main/java/com/checkmarx/flow/dto/azure/ResourceComment.java
  src/main/java/com/checkmarx/flow/dto/azure/Thread.java
  src/main/java/com/checkmarx/flow/dto/github/CxFlowCommandHandler.java
  src/main/java/com/checkmarx/flow/service/ADOCommentService.java
  src/main/java/com/checkmarx/flow/service/ADOConfigService.java
  src/main/java/com/checkmarx/flow/service/ADOService.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
  src/main/java/com/checkmarx/flow/utils/ADOUtils.java
  src/main/java/com/checkmarx/flow/utils/CommonUtils.java
  src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
  src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
  src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
  src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
  src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Labels: size/XXL

#1441 Vulnerabilties fixes
  Dockerfile
  build.gradle
Labels: size/M

#1442 Upgraded SDK version to 0.6.26
  build.gradle
Labels: size/XS

#1444 Few fixes related to jsonIgnore and comments- ADO-PR-Decoration-comments
  src/main/java/com/checkmarx/flow/dto/azure/Resource.java
  src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
Labels: size/XS

#1445 Null check for GitLab Dashboard
  Dockerfile
  src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
Labels: size/L
