Repository checkmarx-ltd/cx-flow, pull requests merged in 2025-02, with the labels that each got.

#1419 CXFLW-1482 Fix for name creation issue in branching
  build.gradle
  docs/Configuration.md
Labels: size/XS

#1422 CXFLW-1590 Fixed issue for Pr feedback false
  src/main/java/com/checkmarx/flow/config/FlowProperties.java
  src/main/java/com/checkmarx/flow/service/ResultsService.java
Labels: size/S

#1424 CXFLW-1536 Added configuration to remove module from URI
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/config/SarifProperties.java
  src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Labels: size/S

#1417 Added logic for deleting CxSCA project
  build.gradle
  docs/Delete-Branch.md
  src/main/java/com/checkmarx/flow/service/ASTScanner.java
  src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
  src/main/java/com/checkmarx/flow/service/FlowService.java
  src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
  src/main/java/com/checkmarx/flow/service/SCAScanner.java
  src/main/java/com/checkmarx/flow/service/SastScanner.java
  src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java
Labels: size/L

#1420 Project deletion support via CLI command
  docs/Execution.md
  src/main/java/com/checkmarx/flow/CxFlowRunner.java
  src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java
Labels: size/M

#1428 updated bitbucketpull documentation
  docs/Tutorials.md
Labels: size/S

#1427 Enhanced PR decoration when restricting results to branch
  build.gradle
  docs/Configuration.md
  src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
  src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
Labels: size/S

#1429 Test cases fix
  build.gradle
  src/test/resources/application.yml
  src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
  src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
  src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
  src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
  src/test/resources/cucumber/features/componentTests/parse.feature
Labels: size/XL

#1430 Added code for execution for test case
  src/main/java/com/checkmarx/flow/dto/github/CxFlowCommandHandler.java
Labels: size/XS

#1431 Updated test cases
  src/main/java/com/checkmarx/flow/service/JiraService.java
  src/test/resources/cucumber/data/sample-sast-results/1-finding-updated.xml
  src/test/resources/cucumber/data/sample-sast-results/different-severities-10-10.xml
  src/test/resources/cucumber/data/sample-sast-results/different-severities-10-5.xml
Labels: size/S

#1432 Vulnerability Fix for 1.7.07
  build.gradle
Labels: size/S
